filtering:
  # Apply a voxel grid filter on incoming point clouds.
  grid_filter: true

  # Resolution of voxel grid filter.
  grid_res: 0.2

  # Apply a random downsample filter on incoming point clouds.
  random_filter: true

  # Percentage of points to discard. Must be between 0.0 and 1.0.
  decimate_percentage: 0.9

  # Apply a statistical outlier filter on incoming point clouds.
  outlier_filter: false

  # Standard deviation threshold in distance to neighbors for outlier removal.
  outlier_std: 1.0

  # Number of nearest neighbors for outlier removal filter.
  outlier_knn: 10

  # Apply a radius filter on incoming point clouds.
  radius_filter: false

  # Size of the radius outlier filter.
  radius: 0.15

  # If this number of neighbors are not found within a radius of a point, remove
  # the point.
  radius_knn: 3
